version: '2'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  redis:
    image: redis
    command: "redis-server --appendonly yes"
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "./wait-for-services.sh && npm run start"
    volumes:
      - ./backend:/myapp
    environment:
      DOCKER_MONGODB_HOST: "mongo"
      DOCKER_REDIS_HOST: "redis"
      JWT_ACCESS_CODE: "yVLkmeMnIMmkGhQ8Lg83ER7EbYQZuOJGmZ0evJ8VmCWfcwGTTtO7d4FK7ytalPYQCXTK3rkagprvXKoz"
    depends_on:
      - mongo
      - redis
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/myapp
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
